language: php

php:
  - '7.2'

before_install:
  - nvm install # Use node version as defined in .nvmrc, for deterministic webpack builds.
  - sudo apt-get install -y librsvg2-bin

install:
  - travis_retry composer install
  - travis_retry npm ci

script:
  # Compile assets, and make sure nothing's changed in Git.
  - node_modules/.bin/encore production
  - git status
  - git status | grep "nothing to commit, working tree clean"
  # Run linting.
  - composer lint
  # Run tests.
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls --coverage_clover=var/log/phpunit_clover.xml --json_path=var/coveralls-upload.json
