version: "3"
services:

  web:
    build:
      dockerfile: ./.docker/web/Dockerfile
      context: .
    ports:
      - 8042:80
    volumes:
      - .:/var/www:cached

  assets:
    image: node:18.19
    working_dir: /svgtranslate
    volumes:
      - ./:/svgtranslate:cached
    command: ./.docker/assets/run.sh

  wiki:
    build:
      dockerfile: ./.docker/wiki/Dockerfile
      context: .
    ports:
      - 8043:80
    volumes:
      - ./var/wiki:/var/www/html/images
      - ./.docker/wiki/LocalSettings.php:/var/www/html/LocalSettings_tmp.php
      - ./.docker/wiki/run.sh:/usr/local/bin/docker-run.sh
    command: /usr/local/bin/docker-run.sh
